# Generated by Django 3.2.5 on 2021-08-03 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Processing', '0002_auto_20210803_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wFile', models.FileField(upload_to='')),
            ],
        ),
    ]
